{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace | default "default" }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
